//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bitirme.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ilan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ilan()
        {
            this.teklif = new HashSet<teklif>();
        }
    
        public int ID { get; set; }
        public string ad { get; set; }
        public System.DateTime baslamaTarih { get; set; }
        public System.DateTime bitisTarih { get; set; }
        public Nullable<double> birimFiyat { get; set; }
        public double boyut { get; set; }
        public int durum { get; set; }
        public int projeID { get; set; }
        public int typeID { get; set; }
        public string foto { get; set; }
    
        public virtual ilanType ilanType { get; set; }
        public virtual proje proje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<teklif> teklif { get; set; }
    }
}
