//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bitirme.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class mesaj
    {
        public int ID { get; set; }
        public string baslik { get; set; }
        public string icerik { get; set; }
        public System.DateTime sendTime { get; set; }
        public int chatID { get; set; }
        public int gonderenID { get; set; }
        public int alanID { get; set; }
    
        public virtual chat chat { get; set; }
        public virtual hesap hesap { get; set; }
        public virtual hesap hesap1 { get; set; }
    }
}
