//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bitirme.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class webinsaatEntities : DbContext
    {
        public webinsaatEntities()
            : base("name=webinsaatEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<hesap> hesap { get; set; }
        public virtual DbSet<hesapType> hesapType { get; set; }
        public virtual DbSet<ilanType> ilanType { get; set; }
        public virtual DbSet<muteahhit> muteahhit { get; set; }
        public virtual DbSet<proje> proje { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<taseron> taseron { get; set; }
        public virtual DbSet<usta> usta { get; set; }
        public virtual DbSet<yonetici> yonetici { get; set; }
        public virtual DbSet<yorum> yorum { get; set; }
        public virtual DbSet<teklif> teklif { get; set; }
        public virtual DbSet<ilan> ilan { get; set; }
        public virtual DbSet<chat> chat { get; set; }
        public virtual DbSet<mesaj> mesaj { get; set; }
    }
}
