//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bitirme.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class teklif
    {
        public int ID { get; set; }
        public int hesapID { get; set; }
        public double fiyat { get; set; }
        public int ilanID { get; set; }
        public int durum { get; set; }
        public int ekipID { get; set; }
    
        public virtual hesap hesap { get; set; }
        public virtual usta usta { get; set; }
        public virtual ilan ilan { get; set; }
    }
}
