//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bitirme.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class usta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usta()
        {
            this.teklif = new HashSet<teklif>();
        }
    
        public int ID { get; set; }
        public int hesapID { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public int taseronID { get; set; }
        public Nullable<int> isSayisi { get; set; }
        public Nullable<int> puan { get; set; }
    
        public virtual hesap hesap { get; set; }
        public virtual taseron taseron { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<teklif> teklif { get; set; }
    }
}
