//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bitirme.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class yorum
    {
        public int ID { get; set; }
        public int hesapID { get; set; }
        public string yorum1 { get; set; }
        public int puan { get; set; }
        public int sahipID { get; set; }
    
        public virtual hesap hesap { get; set; }
    }
}
